
import { GoogleGenAI, Modality } from "@google/genai";

export const getMimeType = (base64: string): string => {
  // A simple check for common image types. This is not foolproof.
  // A more robust solution might involve reading file headers if available.
  const signatures: { [key: string]: string } = {
    '/9j/': 'image/jpeg',
    'iVBORw0KGgo=': 'image/png',
    'R0lGODlh': 'image/gif',
    'UklGR': 'image/webp',
  };
  for (const sig in signatures) {
    if (base64.startsWith(sig)) {
      return signatures[sig];
    }
  }
  return 'image/png'; // Default
};

export const generatePoster = async (
  productImageBase64: string,
  slogan: string,
  aspectRatio: string
): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const prompt = `Create a modern, eye-catching promotional poster for this product. The poster's design should be compelling for an advertising campaign, with a professional and clean aesthetic.
Slogan to include: "${slogan}". Integrate this slogan with stylish, legible typography that complements the overall design.
Ensure the product itself remains clear, high-fidelity, and the main focus.
The final poster must have an aspect ratio of ${aspectRatio}.`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: productImageBase64,
            mimeType: getMimeType(productImageBase64),
          },
        },
        { text: prompt },
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      return part.inlineData.data;
    }
  }
  throw new Error('No image was generated by the model.');
};

const mapPosterRatioToVideoRatio = (posterRatio: string): '16:9' | '9:16' => {
  switch (posterRatio) {
    case '9:16':
    case '3:4':
      return '9:16';
    case '16:9':
    case '1:1':
    case '4:3':
    default:
      return '16:9';
  }
};

export const generateVideoForLocation = async (
  posterImageBase64: string,
  locationPrompt: string,
  posterAspectRatio: string,
  onAuthError: () => void,
): Promise<string> => {
  // Create a new instance for each call to ensure the latest API key is used
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const videoAspectRatio = mapPosterRatioToVideoRatio(posterAspectRatio);
  
  const prompt = `Create a realistic, 5-second video clip showing this poster displayed at: "${locationPrompt}".
The scene should be dynamic, with subtle, natural movements (e.g., people walking by, passing traffic, gentle camera pan).
**Realism Engine Instructions:**
- **Lighting:** Match the poster's illumination perfectly to the ambient light of the location (day/night, sunny/overcast).
- **Perspective & Reflections:** Generate accurate perspective and realistic reflections on the poster's surface, especially if it's behind glass or on a glossy screen.
- **Integration:** Create realistic ambient occlusion and shadows where the poster meets its frame or the surrounding structure.
- **Clarity:** Ensure the poster's content remains clear, legible, and undistorted throughout the video.`;

  try {
    let operation = await ai.models.generateVideos({
      model: 'veo-3.1-fast-generate-preview',
      prompt: prompt,
      image: {
        imageBytes: posterImageBase64,
        mimeType: getMimeType(posterImageBase64),
      },
      config: {
        numberOfVideos: 1,
        resolution: '720p',
        aspectRatio: videoAspectRatio,
      },
    });

    while (!operation.done) {
      await new Promise(resolve => setTimeout(resolve, 10000)); // Poll every 10 seconds
      operation = await ai.operations.getVideosOperation({ operation: operation });
    }

    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (!downloadLink) {
      throw new Error('Video generation finished but no URI was found.');
    }

    const response = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
    if (!response.ok) {
        throw new Error(`Failed to fetch video file: ${response.statusText}`);
    }
    const videoBlob = await response.blob();
    return URL.createObjectURL(videoBlob);
  } catch(error: any) {
      if(error?.message?.includes("Requested entity was not found")) {
          onAuthError();
      }
      console.error("Video generation failed:", error);
      throw error;
  }
};
